Double back press to exit the app #110
fossasia/loklak_wok_android pull request #125
Opened 2019-01-31 10:25 UTC by riyasingh1004

The user needs to press the back button twice to exit the app.

Fix #110 

Changes: [Add here what changes were made in this issue and if possible provide links.]

Screenshots for the change:

2019-02-03 09:58 UTC, championpaddler reviewed
@riyasingh1004  Please fix failing travis.

2019-02-03 12:05 UTC, riyasingh1004 commented
Can you please help me understand why the Travis CI build is failing. When I am running it on my system its working properly.

2019-02-03 12:19 UTC, championpaddler requested changes
@riyasingh1004

2019-02-03 12:19 UTC, sk9331657 commented on app/src/main/java/org/loklak/wok/ui/activity/TweetHarvestingActivity.java
> +import . . .
@riyasingh1004  This is causing the error.

2019-02-03 12:53 UTC, riyasingh1004 commented
The Travis CI check is done but now codecov/patch is showing some error. Can you please explain about it.

2019-02-03 12:56 UTC, sk9331657 commented
> The Travis CI check is done but now codecov/patch is showing some error. Can you please explain about it.

@riyasingh1004  Os.handler package is removed , I supposes.

2019-02-03 12:58 UTC, riyasingh1004 commented
Should I add it?

2019-02-03 13:03 UTC, sk9331657 commented
> Should I add it?
Try .

2019-02-05 05:10 UTC, mariobehling commented
Thank you.

2019-02-05 05:10 UTC, merged