Updates gradle, build tools, compile and target sdk
fossasia/loklak_wok_android pull request #31
Opened 2017-06-05 10:52 UTC by abishekvashok

To ensure smooth development flow and also to ensure that
the app runs quick and takes full profit of new features
like instant run, backward compatibility libraries and
other updates it is needed to update the old versions and
replace them with the newest ones.

Fixes #30

2017-06-06 06:22 UTC, sudheesh001 commented
After successful fetch of gradle and the required jars the build fails because the agreement isn't accepted.
Please do also have a look here https://github.com/travis-ci/travis-ci/issues/7110
```
You have not accepted the license agreements of the following SDK components:
  [Android SDK Platform 25].
```

2017-06-06 06:32 UTC, abishekvashok commented
I am looking into it, Travis CI docs do state that they accept all licenses on code authors behalf or behalf of the community but it's not working for target api 25.

2017-06-07 17:24 UTC, SKrPl commented
5th comment in the link mentioned by @sudheesh001  it states that *build-tool* version should be same in both `.travis.yml` file and `build.gradle` file. I tried that in https://github.com/fossasia/loklak_wok_android/pull/32 and it works fine.

2017-06-07 18:07 UTC, SKrPl requested changes
Please see the comments.

2017-06-07 18:07 UTC, SKrPl commented on .travis.yml
> +  - ADB_INSTALL_TIMEOUT=15 ANDROID_BUILD_TOOLS_VERSION=25.0.3 ANDROID_TARGET=android-25 ANDROID_ABI=armeabi-v7a
Any reasons to remove `ANDROID_TAG` value as this is used [here](https://github.com/fossasia/loklak_wok_android/pull/31/files#diff-354f30a63fb0907d4ad57269548329e3R25)?

2017-06-07 18:07 UTC, SKrPl commented on .travis.yml
> +  - tools
`-tools` is already present. Any specific reasons to add it again? In case you did it by mistake please rectify it.

2017-06-07 18:07 UTC, SKrPl commented on .travis.yml
> +licenses:
I don't think we need to provide license explicitly, as you pointed out.

2017-06-08 08:25 UTC, abishekvashok commented on .travis.yml
> +  - tools
Travis docs recommend to add tools two times: https://docs.travis-ci.com/user/languages/android/#Installing-a-newer-SDK-Platform-Tools-revision: see the note section

2017-06-08 08:26 UTC, abishekvashok commented on .travis.yml
> +licenses:
I was experimenting

2017-06-08 08:27 UTC, abishekvashok commented on .travis.yml
> +  - ADB_INSTALL_TIMEOUT=15 ANDROID_BUILD_TOOLS_VERSION=25.0.3 ANDROID_TARGET=android-25 ANDROID_ABI=armeabi-v7a
Nil, Adding it back

2017-06-08 08:29 UTC, abishekvashok commented
> 5th comment in the link mentioned by @sudheesh001 it states that build-tool version should be same in both .travis.yml file and build.gradle file. I tried that in #32 and it works fine.

Both are using 25.0.3

2017-06-08 11:03 UTC, abishekvashok commented
Done >> Tests passed. Please recheck @SkrPl @sudheesh001

2017-06-10 07:47 UTC, SKrPl commented
Please squash the commits. Good work :+1: .

2017-06-10 08:40 UTC, merged