Adds tweet search suggestion feature
fossasia/loklak_wok_android pull request #32
Opened 2017-06-05 11:54 UTC by SKrPl

Solves issue: https://github.com/fossasia/loklak_wok_android/issues/27

Changes build.gradle files for increasing targetSdk and minSdk, updating
the gradle build tool version and adding support material design,
retrofit, gson and butterknife library.

2017-06-05 12:02 UTC, abishekvashok requested changes
There are other empty constructors as well. See comments, the rest is fine :)

2017-06-05 12:02 UTC, abishekvashok commented on app/build.gradle
> +    buildToolsVersion '25.0.0'
25.0.3 is the latest, can you update to it?

2017-06-05 12:02 UTC, abishekvashok commented on app/build.gradle
> +        minSdkVersion 14
Is there any compatibility problem for SDK 11?

2017-06-05 12:02 UTC, abishekvashok commented on app/src/main/AndroidManifest.xml
> +        <!--<activity android:name=".MainActivity">
Better to remove code than to comment it. (Comment while you test :))

2017-06-05 12:02 UTC, abishekvashok commented on app/src/main/AndroidManifest.xml
> +</manifest>
Don't remove a newline at eof

2017-06-05 12:02 UTC, abishekvashok commented on app/src/main/java/org/loklak/android/adapters/SuggestAdapter.java
> +            // suggestQuery = (TextView) itemView.findViewById(R.id.suggest_query);
Follow up

2017-06-05 12:02 UTC, abishekvashok commented on app/src/main/java/org/loklak/android/model/suggest/Query.java
> +    public Query() {
Empty constructor

2017-06-05 12:02 UTC, abishekvashok commented on app/src/main/java/org/loklak/android/model/suggest/SearchMetadata.java
> +    public SearchMetadata() {
Empty constructor

2017-06-05 12:02 UTC, abishekvashok commented on app/src/main/res/layout/row_tweet_search_suggest.xml
> +</LinearLayout>
Add a newline at eof

2017-06-05 12:03 UTC, abishekvashok commented
Also as you changed build tools and target SDK update them in `.travis.yml`. @SkrPI

2017-06-05 12:05 UTC, SKrPl commented on app/build.gradle
> +        minSdkVersion 14
Yes, material design library requires minSdk to be 14.

2017-06-05 12:18 UTC, SKrPl commented on app/src/main/java/org/loklak/android/model/suggest/Query.java
> +    public Query() {
I will be using RealmDatabase, which requires a constructor to be there.

2017-06-05 12:19 UTC, SKrPl commented on app/build.gradle
> +    buildToolsVersion '25.0.0'
Sure :+1:

2017-06-05 13:05 UTC, abishekvashok commented on app/build.gradle
> +        minSdkVersion 14
Ok

2017-06-05 13:07 UTC, abishekvashok commented on app/build.gradle
> +        minSdkVersion 14
But I read somewhere the up to 11 material design library is backward compatibile

2017-06-05 13:08 UTC, abishekvashok commented on app/src/main/java/org/loklak/android/model/suggest/Query.java
> +    public Query() {
Then can you use the constructor, by putting the initialization of the variables to be done inside the constructor

2017-06-05 15:55 UTC, SKrPl commented on app/build.gradle
> +        minSdkVersion 14
Maybe due to incomplete build it was asking to use minSdk to be 14, but I again retried and it works. Will change it.

2017-06-06 03:53 UTC, abishekvashok commented on app/build.gradle
> +        minSdkVersion 14
Ok

2017-06-07 06:09 UTC, SKrPl commented
@abishekvashok rebased it and have added other 4 functionalities mentioned in the issue.
@Orbiter @sudheesh001 @djmgit Please review it.

2017-06-07 06:37 UTC, djmgit reviewed
@SKrPl lokks good, would be nice if you could add a app acreen shot.

2017-06-07 07:32 UTC, SKrPl commented
![device-2017-06-07-121030](https://user-images.githubusercontent.com/12163892/26865433-575324fa-4b7a-11e7-9600-eedd498ccf40.png)

2017-06-07 08:01 UTC, djmgit commented
@SKrPl looks nice, please check the travis failure

2017-06-07 10:10 UTC, abishekvashok commented
Yea pls check travis

2017-06-18 18:03 UTC, SKrPl commented
@abishekvashok  @djmgit rebased it, solved some of the lint issues.

2017-06-19 10:55 UTC, abishekvashok commented on app/src/main/AndroidManifest.xml
> +</manifest>
Add a newline at eof

2017-06-19 11:27 UTC, SKrPl commented
@abishekvashok Added newline at eof in manifest.xml

2017-06-19 11:52 UTC, abishekvashok approved these changes
It works

2017-06-19 15:20 UTC, mariobehling commented
@SKrPl Please work more closely together with other developers to get your PRs reviewed and provide a scrum that let's others follow up more easily.

2017-06-19 15:20 UTC, merged