[WIP] Replace Processing.org's applet
fossasia/loklak_wok_android pull request #35
Opened 2017-06-19 23:56 UTC by SKrPl

Partially solves issue: https://github.com/fossasia/loklak_wok_android/issues/34

Added twitter.js (transpiled and bundled) as a raw resource. The added
resource is used by LiquidCore to respond to events. Number of fetched tweets are displayed in log.

2017-06-27 10:58 UTC, abishekvashok requested changes

2017-06-27 10:58 UTC, abishekvashok commented on app/build.gradle
> +    compile 'com.github.LiquidPlayer:LiquidCore:0.2.2'
Use implementation instead. `compile` is depreciated.

2017-06-28 14:44 UTC, abishekvashok requested changes

2017-06-28 14:44 UTC, abishekvashok commented on build.gradle
> +        classpath 'com.android.tools.build:gradle:2.3.3'
Pls use the latest one: 4.0

2017-06-29 22:16 UTC, SKrPl commented on build.gradle
> +        classpath 'com.android.tools.build:gradle:2.3.3'
How do I update?

2017-06-30 00:45 UTC, SKrPl commented
@Orbiter @sudheesh001 @mariobehling @daminisatya @abishekvashok @Achint08 @djmgit @hemantjadon @kavithaenair @SarishiNoHara @singhpratyush @vibhcool Please review it.

![device-2017-06-30-060008](https://user-images.githubusercontent.com/12163892/27716346-64e12f52-5d5b-11e7-9ceb-c3463daae606.png)

2017-06-30 05:54 UTC, abishekvashok commented on build.gradle
> +        classpath 'com.android.tools.build:gradle:2.3.3'
Change 2.3.3 to 4.0
IDE will download the grade version for you.

2017-06-30 06:10 UTC, abishekvashok requested changes

2017-06-30 06:10 UTC, abishekvashok commented on app/build.gradle
> +    compile 'com.squareup.okhttp3:logging-interceptor:3.7.0'
Pls use implementation instead as compile is deprecated.

2017-06-30 06:10 UTC, abishekvashok commented on app/src/main/res/layout/fragment_tweet_harvesting.xml
> +</RelativeLayout>
Always add a newline at eof

2017-06-30 06:10 UTC, abishekvashok commented on app/src/main/res/menu/menu_tweet_harvesting.xml
> +</menu>
New line

2017-06-30 07:42 UTC, kavithaenair commented on app/build.gradle
> +    // This is compilet, it will run lint checks but won't abort build
Typo.

2017-06-30 07:42 UTC, kavithaenair commented on app/src/main/res/layout/row_harvested_tweet.xml
> +</android.support.v7.widget.CardView>
New line.

2017-06-30 07:42 UTC, kavithaenair commented on app/src/main/res/drawable/ic_search_24dp.xml
> +        android:pathData="M15.5,14h-0.79l-0.28,-0.27C15.41,12.59 16,11.11 16,9.5 16,5.91 13.09,3 9.5,3S3,5.91 3,9.5 5.91,16 9.5,16c1.61,0 3.09,-0.59 4.23,-1.57l0.27,0.28v0.79l5,4.99L20.49,19l-4.99,-5
Avoid lengthy lines.

2017-06-30 08:38 UTC, singhpratyush requested changes
The `twitter.js` file is huge. I think that webpack should be configured in a way that it produces a compressed version of bundled `js` (see [here](https://hackernoon.com/optimising-your-application-bundle-size-with-webpack-e85b00bab579) for help).

Also, to avoid the pain of updating everytime `loklak_js_scrapers` change, we should create an autobuild at separate branch using Travis and let apps use the resources from there.

@Achint08 @hemantjadon @SKrPl: What are your views on this?

2017-07-01 06:16 UTC, SKrPl commented
@singhpratyush I have used `-p` flag for bundling, I will look into additionals provided in the blog.
Can you elaborate a bit on "we should create an autobuild at separate branch using Travis and let apps use the resources from there"?
The `twitter.js` file can't be kept on a separate branch, it needs to be on the same branch, so LiquidCore can parse it for execution.

2017-07-01 06:23 UTC, SKrPl commented on build.gradle
> +        classpath 'com.android.tools.build:gradle:2.3.3'
To use version `4.0` the users need to have Android Studio 3.0+ which is still a beta release, most of the users stick to a stable release - current stable release 2.3.3, and Android Studio below 3.x can't use the new gradle versions (links: [Android dev](https://developer.android.com/studio/preview/features/new-android-plugin-migration.html) and [SO](https://stackoverflow.com/questions/44580320/how-to-use-gradle-4-0-in-android-studio-2-3)). So, I think its better to stick with `2.3.3` till Android Studio 3.0 becomes a stable release :smile: .

2017-07-01 06:24 UTC, SKrPl commented on app/build.gradle
> +    compile 'com.squareup.okhttp3:logging-interceptor:3.7.0'
Can't be used with the current stable version of Android Studio.

2017-07-01 06:25 UTC, singhpratyush commented
> [<span>@singhpratyush</span>](https://github.com/singhpratyush) I have used `-p` flag for bundling, I will look into additionals provided in the blog.

:+1: 

> Can you elaborate a bit on "we should create an autobuild at separate branch using Travis and let apps use the resources from there"?
The `twitter.js` file can't be kept on a separate branch, it needs to be on the same branch, so LiquidCore can parse it for execution.

I apologise for the abstract mention, please let me explain in detail about what flow I am proposing - 

1. The successful build at master of `loklak_scrapers_js` builds several bundled `js` and pushes it to another branch (say `bundles`) with proper versioning (maybe `<bundle_name>_v<travis_build_number>.<extension>`).
  We can also think about making automatic releases for this.

2. The app tries to see if it already has the bundle. If no, it can request the branch/release for latest version of the bundle and parse it with `LiquidCore`.
  Automatic, periodic updates would also be required.

@Achint08 @hemantjadon @SKrPl: Please let me know if I am missing something.

2017-07-01 06:29 UTC, SKrPl commented on app/src/main/res/drawable/ic_search_24dp.xml
> +        android:pathData="M15.5,14h-0.79l-0.28,-0.27C15.41,12.59 16,11.11 16,9.5 16,5.91 13.09,3 9.5,3S3,5.91 3,9.5 5.91,16 9.5,16c1.61,0 3.09,-0.59 4.23,-1.57l0.27,0.28v0.79l5,4.99L20.49,19l-4.99,-5
It's a vector image file generated by Android Studio. In general practice, it is left as it is generated.

2017-07-03 03:31 UTC, hemantjadon commented on build.gradle
> +        classpath 'com.android.tools.build:gradle:2.3.3'
@abishekvashok @SKrPl Stick to Stable I guess

2017-07-04 03:31 UTC, singhpratyush approved these changes
I guess it we should proceed with this and make the changes when https://github.com/fossasia/loklak_scraper_js/issues/36 gets fixed.

2017-07-04 03:32 UTC, SKrPl commented
As per the discussions and suggestions on "Automating the addition of bundled scraper in this project" (link: https://github.com/fossasia/loklak_scraper_js/issues/36), as of now bundled scraper file will be added to loklak_wok_android manually.

2017-07-04 03:33 UTC, singhpratyush commented
@SKrPl: Also, try to make smaller PRs as it they would be easy to review :sweat_smile:.

2017-07-04 03:36 UTC, SKrPl commented
@singhpratyush I will try my best to do that from next time onwards, this was a big feature, and making different PRs could have resulted in a lot of merge conflicts, as I changed the code frequently.

2017-07-04 04:03 UTC, SKrPl commented
@kavithaenair @abishekvashok Added new lines at the end of mentioned files and squashed the commits.

2017-07-04 13:44 UTC, kavithaenair approved these changes

2017-07-04 19:41 UTC, vibhcool approved these changes
looks good to me

2017-07-05 05:18 UTC, sudheesh001 commented
Please squash the commits.

2017-07-05 05:37 UTC, SKrPl commented
@sudheesh001 done :smile:.

2017-07-05 05:38 UTC, daminisatya approved these changes
(Y)

2017-07-05 05:50 UTC, merged