[WIP] Fixes #33: Adds tweet search feature
fossasia/loklak_wok_android pull request #37
Opened 2017-07-05 04:43 UTC by SKrPl

Related issue: https://github.com/fossasia/loklak_wok_android/issues/33
Creates the UI of a row which displays the tweet and POJO for "search"
loklak API.

2017-07-05 11:57 UTC, abishekvashok requested changes

2017-07-05 11:57 UTC, abishekvashok commented on app/build.gradle
> +    compile 'com.android.support:cardview-v7:25.3.1'
Use `implementation` instead of `compile`

2017-07-11 02:38 UTC, SKrPl commented on app/build.gradle
> +    compile 'com.android.support:cardview-v7:25.3.1'
Implementation is not a stable version. So, I think we should stick to compile.

2017-07-11 02:47 UTC, SKrPl commented
![device-2017-07-11-081432](https://user-images.githubusercontent.com/12163892/28048824-0c1778ea-6611-11e7-83fe-f1f123e3a144.png)

I haven't added website and video preview as of now, I will create a new issue for that. This PR only solves adds the functionality of tweet searching.

2017-07-11 02:48 UTC, SKrPl commented
@mariobehling @Orbiter @sudheesh001 @daminisatya @abishekvashok @Achint08 @djmgit @hemantjadon @kavithaenair @singhpratyush @vibhcool Please review.

2017-07-11 03:10 UTC, singhpratyush commented
@SKrPl: The code looks clean and good. Can you please provide a link to the corresponding APK?

2017-07-11 05:28 UTC, SKrPl commented
.apk file link: https://drive.google.com/open?id=0B_L50ue18BeuaUlpTjllalpaZGc

2017-07-11 10:13 UTC, Achint08 commented
@SKrPl Images/Videos are not showing up. It is just a tabs implementation, right?

2017-07-11 10:26 UTC, SKrPl commented
@Achint08 as of now only the actually uploaded images and videos will be shown. Using the `filter` parameter of `search` API endpoint provides image tweets that contains website preview and same goes for videos also (youtube). So, this PR doesn't deal with showing website image preview. I will create a separate issue for that and work on that.

2017-07-11 10:54 UTC, Achint08 commented on app/src/main/res/drawable/reply.xml
> +</vector>
A new line at the end of the file.

2017-07-11 10:55 UTC, Achint08 commented on app/src/main/res/drawable/heart.xml
> +</vector>
Here also

2017-07-11 10:57 UTC, Achint08 commented
@SKrPl Switching to a new filter shows up `Please Check your internet connection.` Kindly check this.

2017-07-12 01:52 UTC, SKrPl commented
@Achint08 that happens when a NetworkIO exception is encountered. Tapping on the TextView resends the get request. And the views get populated if there is no network error again.

2017-07-12 05:50 UTC, singhpratyush commented
@SKrPl: I see the same picture across many Tweets in the `Image` view. Is there a placeholder?

2017-07-12 06:11 UTC, Achint08 approved these changes
LGTM 👍

2017-07-12 06:16 UTC, SKrPl commented
@singhpratyush no there is no placeholder, can you provide a screenshot?

2017-07-12 06:32 UTC, singhpratyush commented
@SKrPl: It seems like those Tweets actually had the same image. It is working fine for other queries. Sorry for the false alarm.

2017-07-12 06:33 UTC, singhpratyush approved these changes

2017-07-12 10:09 UTC, merged