Fixes #62: Adds touch selectors for buttons
fossasia/loklak_wok_android pull request #65
Opened 2017-08-13 08:09 UTC by SKrPl

Adds touch selector for media buttons and tweet button in
TweetPostingFragment. The media buttons have the background "#BDBDBD"
and tweet button has the background "#F48FB1" which is also the light
accent color.

2017-08-13 08:10 UTC, SKrPl commented
@Achint08 @djmgit @hemantjadon @kavithaenair @singhpratyush @vibhcool Please review.

2017-08-16 03:13 UTC, singhpratyush approved these changes

2017-08-16 03:34 UTC, kavithaenair approved these changes

2017-08-16 04:38 UTC, djmgit approved these changes

2017-08-16 06:34 UTC, Achint08 approved these changes

2017-08-16 06:48 UTC, sudheesh001 requested changes
Changes are fine, You should upload a screenshot into the PR description on github so that we can trace it back to this in case of issues.

2017-08-16 09:37 UTC, mariobehling commented
Screenshot? Please follow best practices.

2017-08-17 15:08 UTC, SKrPl commented
@sudheesh001 @mariobehling rebased and Updated PR description with GIF.

2017-08-17 17:30 UTC, djmgit approved these changes

2017-08-17 20:56 UTC, vibhcool approved these changes

2017-08-17 22:02 UTC, merged