Fixes #68: Proper image scaling & button alignment
fossasia/loklak_wok_android pull request #69
Opened 2017-08-17 16:20 UTC by SKrPl

Selected images from gallery are scaled properly and the media buttons
are aligned with "Tweet" button and number of remaining characters
TextView.

### After fix
![20945542_1929446207342770_1341483227_o](https://user-images.githubusercontent.com/12163892/29422490-0284af9e-8396-11e7-8913-9104abc8ff9e.png)

2017-08-17 16:21 UTC, SKrPl commented
@abishekvashok @Achint08 @djmgit @hemantjadon @kavithaenair @singhpratyush @vibhcool Please review.

2017-08-17 20:56 UTC, vibhcool approved these changes

2017-08-17 21:22 UTC, singhpratyush approved these changes

2017-08-18 00:03 UTC, Achint08 approved these changes

2017-08-18 03:44 UTC, abishekvashok commented on app/src/main/res/values/dimens.xml
> +    <dimen name="tweet_media_remove_margin">8dp</dimen>
Can you make this more precise. I meant why was the remove used?

2017-08-18 04:09 UTC, sudheesh001 requested changes
Looks decent, but a few design changes to be made. the Tweet button isn't the same height as the other buttons in it's row. The color of the button is what makes it stand out as an important button.

However, change this button to be the same height as the rest of the buttons. Also can you make it have rounded edges, basically which looks like a rectangle in the middle with 2 semicircles to both sides.

![tweet](https://user-images.githubusercontent.com/4545925/29443930-2fbaaae6-83f9-11e7-8485-955b734fcf2d.PNG)

2017-08-18 06:13 UTC, SKrPl commented on app/src/main/res/values/dimens.xml
> +    <dimen name="tweet_media_remove_margin">8dp</dimen>
`tweet_media_remove...` specifies the dimension of the small black circular button present at the top right of an image, clicking on which removes the selected image. So, as it has the functionality to remove things, I used `remove`.

2017-08-20 09:35 UTC, SKrPl commented
@sudheesh001 Implemented the suggested changes and updated the image in PR description.

2017-08-21 04:34 UTC, sudheesh001 approved these changes

2017-08-21 05:27 UTC, kavithaenair approved these changes

2017-08-21 05:29 UTC, djmgit approved these changes

2017-08-21 07:29 UTC, jigyasa-grover approved these changes

2017-08-21 07:29 UTC, merged